### ISSUE TITLE
建議提供ansible-playbook 方便測試人員安裝

### ISSUE THREAD

**Issue by liao-chianan** [fossnio/tp_yass_report_issues#2]
建議提供ansible-playbook _方便測試人員安裝

**Comment by williamwu0220** [comment]
已建立 https://github.com/tcenc/ansible-tp-yass 撰寫安裝/升級用的 ansible role

**Comment by williamwu0220** [comment]
現在可以用 ansible-playbook develop.yml 建置開發環境了，不過意外發現到另外一個問題，待處理好就可以使用。
