### ISSUE TITLE
好站連結是否會開新視窗開啟連結

### ISSUE THREAD

**Issue by chuang18** [fossnio/tp_yass_report_issues#8]
目前好站連結的開啟方式是否可以選擇在新視窗中開啟連結的方式來處理?

**Comment by chuang18** [comment]
抱歉了解設定方式了!

**Comment by williamwu0220** [comment]
好的，那我就先結案 ^^

**Comment by chuang18** [comment]
謝謝老師，辛苦了!

William Wu <notifications@github.com> 於 2020年8月26日 週三 上午10:04寫道：
